version: "3.7"

services:
  api:
    build: api
    environment:
      - ROOT_PATH
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./api/conf/nginx:/etc/nginx/conf.d/
      - ./api/src:${ROOT_PATH}